export const mainCourse = [
  {
    name: 'Chicken Curry',
    image: require('../foodpic/meal/chicken-curry.jpg'),
    servings: 4,
    ingredients: [
      { name: 'chicken pieces', quantity: 1, unit: 'kg' },
      { name: 'coconut milk', quantity: 1, unit: 'can' },
      { name: 'potatoes', quantity: 2, unit: 'pieces' },
      { name: 'carrots', quantity: 1, unit: 'piece' },
      { name: 'curry powder', quantity: 2, unit: 'tablespoons' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'fish sauce', quantity: 1, unit: 'tablespoon' },
      { name: 'oil', quantity: 2, unit: 'tablespoons' },
    ],
    nutrients: {
      calories: 'Approximately 450 per serving',
      protein: 'Approximately 35g',
      fats: 'Approximately 25g',
      carbohydrates: 'Approximately 20g',
      fiber: 'Approximately 2g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin C', 'Vitamin B6'],
      minerals: ['Iron', 'Potassium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Heat oil in a pan and sauté onion and garlic until fragrant.',
      'Add chicken pieces and cook until slightly browned.',
      'Stir in curry powder and mix well.',
      'Add coconut milk and let it simmer.',
      'Add potatoes and carrots, cooking until tender.',
      'Season with fish sauce to taste.',
      'Serve hot with steamed rice.',
    ],
  },
  {
    name: 'Pork Adobo',
    image: require('../foodpic/meal/pork-adobo.jpg'),
    servings: 4,
    ingredients: [
      { name: 'pork belly', quantity: 1, unit: 'kg' },
      { name: 'soy sauce', quantity: 1/2, unit: 'cup' },
      { name: 'vinegar', quantity: 1/4, unit: 'cup' },
      { name: 'garlic', quantity: 5, unit: 'cloves' },
      { name: 'bay leaves', quantity: 2, unit: 'pieces' },
      { name: 'peppercorns', quantity: 1, unit: 'teaspoon' },
      { name: 'water', quantity: 1, unit: 'cup' },
    ],
    nutrients: {
      calories: 'Approximately 500 per serving',
      protein: 'Approximately 40g',
      fats: 'Approximately 35g',
      carbohydrates: 'Approximately 5g',
      fiber: 'Approximately 1g',
    },
    other: {
      vitamins: ['Vitamin B12', 'Niacin'],
      minerals: ['Iron', 'Zinc'],
      otherNutrients: ['Collagen'],
    },
    instructions: [
      'In a pot, combine pork, soy sauce, garlic, bay leaves, and peppercorns. Marinate for at least 30 minutes.',
      'Bring to a boil, then lower heat and simmer until pork is tender.',
      'Add vinegar and let it simmer without stirring.',
      'Continue cooking until the sauce thickens.',
      'Serve with steamed rice.',
    ],
  },
  {
    name: 'Pork Steak',
    image: require('../foodpic/meal/pork-steak.jpg'),
    servings: 4,
    ingredients: [
      { name: 'pork chops', quantity: 4, unit: 'pieces' },
      { name: 'soy sauce', quantity: 1/3, unit: 'cup' },
      { name: 'lemon juice', quantity: 2, unit: 'tablespoons' },
      { name: 'onions', quantity: 2, unit: 'pieces' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'black pepper', quantity: 1, unit: 'teaspoon' },
      { name: 'water', quantity: 1/2, unit: 'cup' },
    ],
    nutrients: {
      calories: 'Approximately 480 per serving',
      protein: 'Approximately 38g',
      fats: 'Approximately 30g',
      carbohydrates: 'Approximately 10g',
      fiber: 'Approximately 1g',
    },
    other: {
      vitamins: ['Vitamin B6', 'Vitamin C'],
      minerals: ['Iron', 'Selenium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Marinate pork chops in soy sauce, lemon juice, and garlic for at least 30 minutes.',
      'Heat oil in a pan and fry pork chops until browned.',
      'Add marinade and water, then let it simmer until meat is tender.',
      'Add onion rings and cook for a few minutes.',
      'Serve with steamed rice.',
    ],
  },
  {
    name: 'Giniling',
    image: require('../foodpic/meal/giniling.jpg'),
    servings: 4,
    ingredients: [
      { name: 'ground pork', quantity: 500, unit: 'g' },
      { name: 'tomato sauce', quantity: 1, unit: 'cup' },
      { name: 'potato', quantity: 1, unit: 'piece' },
      { name: 'carrot', quantity: 1, unit: 'piece' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'soy sauce', quantity: 2, unit: 'tablespoons' },
      { name: 'water', quantity: 1/2, unit: 'cup' },
    ],
    nutrients: {
      calories: 'Approximately 350 per serving',
      protein: 'Approximately 30g',
      fats: 'Approximately 15g',
      carbohydrates: 'Approximately 20g',
      fiber: 'Approximately 3g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin C'],
      minerals: ['Iron', 'Potassium'],
      otherNutrients: ['Beta-Carotene'],
    },
    instructions: [
      'Sauté garlic and onion in a pan.',
      'Add ground pork and cook until browned.',
      'Add tomato sauce and water, then let simmer.',
      'Add diced potatoes and carrots. Cook until tender.',
      'Season with soy sauce and serve with rice.',
    ],
  },
  {
    name: 'Bicol Express',
    image: require('../foodpic/meal/bicol-express.jpg'),
    servings: 4,
    ingredients: [
      { name: 'pork belly', quantity: 1, unit: 'kg' },
      { name: 'coconut milk', quantity: 1, unit: 'can' },
      { name: 'chili peppers', quantity: 5, unit: 'pieces' },
      { name: 'garlic', quantity: 4, unit: 'cloves' },
      { name: 'ginger', quantity: 1, unit: 'tablespoon' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'shrimp paste', quantity: 1, unit: 'tablespoon' },
      { name: 'oil', quantity: 2, unit: 'tablespoons' },
    ],
    nutrients: {
      calories: 'Approximately 550 per serving',
      protein: 'Approximately 42g',
      fats: 'Approximately 38g',
      carbohydrates: 'Approximately 8g',
      fiber: 'Approximately 2g',
    },
    other: {
      vitamins: ['Vitamin C', 'Vitamin B6'],
      minerals: ['Iron', 'Sodium'],
      otherNutrients: ['Capsaicin'],
    },
    instructions: [
      'Sauté garlic, onion, and ginger in oil.',
      'Add pork belly and cook until lightly browned.',
      'Stir in shrimp paste and mix well.',
      'Pour in coconut milk and bring to a simmer.',
      'Add chili peppers and continue cooking until sauce thickens.',
      'Serve with rice.',
    ],
  },
  {
    name: 'Adobong Sitaw',
    image: require('../foodpic/meal/adobong-sitaw.jpg'),
    servings: 4,
    ingredients: [
      { name: 'string beans (sitaw)', quantity: 300, unit: 'g' },
      { name: 'pork belly', quantity: 200, unit: 'g' },
      { name: 'soy sauce', quantity: 3, unit: 'tablespoons' },
      { name: 'vinegar', quantity: 2, unit: 'tablespoons' },
      { name: 'garlic', quantity: 4, unit: 'cloves' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'oil', quantity: 1, unit: 'tablespoon' },
      { name: 'water', quantity: 1, unit: 'cup' },
      { name: 'black pepper', quantity: 1, unit: 'teaspoon' },
    ],
    nutrients: {
      calories: 'Approximately 300 per serving',
      protein: 'Approximately 20g',
      fats: 'Approximately 15g',
      carbohydrates: 'Approximately 18g',
      fiber: 'Approximately 3g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin C', 'Vitamin B6'],
      minerals: ['Iron', 'Calcium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Heat oil in a pan and sauté garlic and onion.',
      'Add pork belly and cook until browned.',
      'Pour in soy sauce and vinegar, then let it simmer.',
      'Add water and bring to a boil.',
      'Toss in the string beans and cook until tender.',
      'Season with black pepper to taste.',
      'Serve hot with rice.',
    ],
  },
  {
    name: 'Sinigang',
    image: require('../foodpic/meal/sinigang.jpg'),
    servings: 4,
    ingredients: [
      { name: 'pork ribs', quantity: 500, unit: 'g' },
      { name: 'tamarind paste', quantity: 3, unit: 'tablespoons' },
      { name: 'water', quantity: 6, unit: 'cups' },
      { name: 'tomatoes', quantity: 2, unit: 'pieces' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'kangkong (water spinach)', quantity: 1, unit: 'bunch' },
      { name: 'radish', quantity: 1, unit: 'piece' },
      { name: 'eggplant', quantity: 1, unit: 'piece' },
      { name: 'green chili', quantity: 2, unit: 'pieces' },
      { name: 'fish sauce', quantity: 2, unit: 'tablespoons' },
      { name: 'salt', quantity: 'to taste' },
    ],
    nutrients: {
      calories: 'Approximately 400 per serving',
      protein: 'Approximately 30g',
      fats: 'Approximately 20g',
      carbohydrates: 'Approximately 25g',
      fiber: 'Approximately 4g',
    },
    other: {
      vitamins: ['Vitamin C', 'Vitamin B6', 'Vitamin K'],
      minerals: ['Iron', 'Calcium', 'Potassium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Boil water in a pot and add pork ribs.',
      'Simmer until pork is tender, skimming off impurities.',
      'Add onions, tomatoes, and tamarind paste. Continue simmering.',
      'Toss in radish, eggplant, and green chili.',
      'Season with fish sauce and salt to taste.',
      'Add kangkong leaves before turning off the heat.',
      'Serve hot with rice.',
    ],
  },
  {
    name: 'Dinuguan',
    image: require('../foodpic/meal/dinuguan.jpg'),
    servings: 4,
    ingredients: [
      { name: 'pork belly', quantity: 300, unit: 'g' },
      { name: 'pork blood', quantity: 1, unit: 'cup' },
      { name: 'vinegar', quantity: 2, unit: 'tablespoons' },
      { name: 'garlic', quantity: 4, unit: 'cloves' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'water', quantity: 2, unit: 'cups' },
      { name: 'bay leaf', quantity: 2, unit: 'pieces' },
      { name: 'green chili', quantity: 1, unit: 'piece' },
      { name: 'salt', quantity: 'to taste' },
      { name: 'black pepper', quantity: 'to taste' },
      { name: 'oil', quantity: 1, unit: 'tablespoon' },
    ],
    nutrients: {
      calories: 'Approximately 350 per serving',
      protein: 'Approximately 25g',
      fats: 'Approximately 20g',
      carbohydrates: 'Approximately 10g',
      fiber: 'Approximately 1g',
    },
    other: {
      vitamins: ['Vitamin B12', 'Vitamin A'],
      minerals: ['Iron', 'Zinc'],
      otherNutrients: ['Collagen'],
    },
    instructions: [
      'Heat oil in a pan and sauté garlic and onion.',
      'Add pork belly and cook until browned.',
      'Pour in vinegar and let it simmer without stirring.',
      'Add water and bay leaves, then simmer until pork is tender.',
      'Slowly add pork blood while stirring continuously.',
      'Season with salt, pepper, and green chili.',
      'Serve hot with rice or puto.',
    ],
  },
  {
    name: 'Ginataang Langka',
    image: require('../foodpic/meal/ginataang-langka.jpg'),
    servings: 4,
    ingredients: [
      { name: 'unripe jackfruit (langka)', quantity: 500, unit: 'g' },
      { name: 'coconut milk', quantity: 2, unit: 'cups' },
      { name: 'garlic', quantity: 3, unit: 'cloves' },
      { name: 'onion', quantity: 1, unit: 'piece' },
      { name: 'ginger', quantity: 1, unit: 'thumb-sized' },
      { name: 'shrimp or dried fish', quantity: 100, unit: 'g' },
      { name: 'green chili', quantity: 2, unit: 'pieces' },
      { name: 'salt', quantity: 'to taste' },
      { name: 'black pepper', quantity: 'to taste' },
    ],
    nutrients: {
      calories: 'Approximately 320 per serving',
      protein: 'Approximately 15g',
      fats: 'Approximately 18g',
      carbohydrates: 'Approximately 25g',
      fiber: 'Approximately 5g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin C'],
      minerals: ['Calcium', 'Potassium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Heat coconut milk in a pot and bring to a simmer.',
      'Add garlic, onion, and ginger, cooking until fragrant.',
      'Toss in unripe jackfruit and mix well.',
      'Add shrimp or dried fish and simmer until cooked.',
      'Season with salt and black pepper.',
      'Add green chilies for spice and mix well.',
      'Serve hot with rice.',
    ],
  },
];

export const dessert = [
  {
    name: 'Buko Salad',
    image: require('../foodpic/dessert/buko-salad.jpg'),
    servings: 6,
    ingredients: [
      { name: 'young coconut (buko), shredded', quantity: 2, unit: 'cups' },
      { name: 'fruit cocktail', quantity: 1, unit: 'can' },
      { name: 'sweetened condensed milk', quantity: 1, unit: 'can' },
      { name: 'all-purpose cream', quantity: 1, unit: 'cup' },
      { name: 'nata de coco', quantity: 1, unit: 'cup' },
      { name: 'kaong (sugar palm fruit)', quantity: 1, unit: 'cup' },
      { name: 'cheese (optional)', quantity: 1, unit: 'cup' },
    ],
    nutrients: {
      calories: 'Approximately 350 per serving',
      protein: 'Approximately 4g',
      fats: 'Approximately 18g',
      carbohydrates: 'Approximately 40g',
      fiber: 'Approximately 3g',
    },
    other: {
      vitamins: ['Vitamin C', 'Vitamin A'],
      minerals: ['Calcium', 'Potassium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Drain fruit cocktail, nata de coco, and kaong.',
      'In a large bowl, mix shredded buko, fruit cocktail, nata de coco, and kaong.',
      'Pour in condensed milk and all-purpose cream. Mix well.',
      'Top with grated cheese if desired.',
      'Chill in the refrigerator before serving.',
    ],
  },
  {
    name: 'Buko Pandan',
    image: require('../foodpic/dessert/buko-pandan.jpg'),
    servings: 6,
    ingredients: [
      { name: 'young coconut (buko), shredded', quantity: 2, unit: 'cups' },
      { name: 'pandan-flavored gelatin', quantity: 1, unit: 'pack' },
      { name: 'water', quantity: 3, unit: 'cups' },
      { name: 'sweetened condensed milk', quantity: 1, unit: 'can' },
      { name: 'all-purpose cream', quantity: 1, unit: 'cup' },
      { name: 'nata de coco', quantity: 1, unit: 'cup' },
    ],
    nutrients: {
      calories: 'Approximately 320 per serving',
      protein: 'Approximately 3g',
      fats: 'Approximately 15g',
      carbohydrates: 'Approximately 45g',
      fiber: 'Approximately 2g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin C'],
      minerals: ['Calcium', 'Potassium'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Dissolve pandan-flavored gelatin in water and bring to a boil.',
      'Pour into a mold and let it set. Once firm, cut into cubes.',
      'In a bowl, mix shredded buko, nata de coco, and gelatin cubes.',
      'Pour in condensed milk and all-purpose cream. Mix well.',
      'Chill before serving.',
    ],
  },
  {
    name: 'Banana Cue',
    image: require('../foodpic/dessert/bananacue.jpg'),
    servings: 4,
    ingredients: [
      { name: 'saba bananas', quantity: 8, unit: 'pieces' },
      { name: 'brown sugar', quantity: 1, unit: 'cup' },
      { name: 'cooking oil', quantity: 2, unit: 'cups' },
    ],
    nutrients: {
      calories: 'Approximately 250 per serving',
      protein: 'Approximately 2g',
      fats: 'Approximately 5g',
      carbohydrates: 'Approximately 50g',
      fiber: 'Approximately 4g',
    },
    other: {
      vitamins: ['Vitamin B6', 'Vitamin C'],
      minerals: ['Potassium', 'Magnesium'],
      otherNutrients: ['Natural Sugars'],
    },
    instructions: [
      'Heat oil in a pan.',
      'Fry bananas until slightly golden.',
      'Add brown sugar and let it caramelize, coating the bananas.',
      'Skewer the bananas and serve hot.',
    ],
  },
  {
    name: 'Ube Halaya',
    image: require('../foodpic/dessert/ube-halaya.jpg'),
    servings: 6,
    ingredients: [
      { name: 'grated purple yam (ube)', quantity: 2, unit: 'cups' },
      { name: 'sweetened condensed milk', quantity: 1, unit: 'can' },
      { name: 'evaporated milk', quantity: 1, unit: 'can' },
      { name: 'butter', quantity: 1, unit: 'tablespoon' },
      { name: 'sugar', quantity: 1, unit: 'cup' },
    ],
    nutrients: {
      calories: 'Approximately 280 per serving',
      protein: 'Approximately 5g',
      fats: 'Approximately 8g',
      carbohydrates: 'Approximately 45g',
      fiber: 'Approximately 3g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin C'],
      minerals: ['Calcium', 'Iron'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'Melt butter in a pan.',
      'Add grated ube and cook for a few minutes.',
      'Pour in condensed milk and evaporated milk. Stir well.',
      'Add sugar and continue stirring until thickened.',
      'Transfer to a container and let it cool.',
      'Serve chilled or at room temperature.',
    ],
  },
  {
    name: 'Halo-Halo',
    image: require('../foodpic/dessert/halo-halo.jpg'),
    servings: 2,
    ingredients: [
      { name: 'shaved ice', quantity: 2, unit: 'cups' },
      { name: 'evaporated milk', quantity: 1, unit: 'cup' },
      { name: 'sweetened beans', quantity: 1, unit: 'cup' },
      { name: 'nata de coco', quantity: 1, unit: 'cup' },
      { name: 'kaong', quantity: 1, unit: 'cup' },
      { name: 'ube halaya', quantity: 2, unit: 'tablespoons' },
      { name: 'leche flan', quantity: 2, unit: 'slices' },
      { name: 'langka (jackfruit)', quantity: 1, unit: 'cup' },
      { name: 'sago and gulaman', quantity: 1, unit: 'cup' },
      { name: 'ube ice cream', quantity: 2, unit: 'scoops' },
    ],
    nutrients: {
      calories: 'Approximately 400 per serving',
      protein: 'Approximately 6g',
      fats: 'Approximately 12g',
      carbohydrates: 'Approximately 70g',
      fiber: 'Approximately 5g',
    },
    other: {
      vitamins: ['Vitamin C', 'Vitamin A'],
      minerals: ['Calcium', 'Iron'],
      otherNutrients: ['Antioxidants'],
    },
    instructions: [
      'In a tall glass, layer sweetened beans, nata de coco, kaong, and jackfruit.',
      'Add shaved ice on top.',
      'Pour evaporated milk over the ice.',
      'Top with ube halaya, leche flan, and ube ice cream.',
      'Mix well before eating.',
    ],
  },
  {
    name: 'Leche Flan',
    image: require('../foodpic/dessert/leche-flan.jpg'),
    servings: 6,
    ingredients: [
      { name: 'egg yolks', quantity: 10, unit: 'pieces' },
      { name: 'sweetened condensed milk', quantity: 1, unit: 'can' },
      { name: 'evaporated milk', quantity: 1, unit: 'can' },
      { name: 'sugar', quantity: 1, unit: 'cup' },
      { name: 'vanilla extract', quantity: 1, unit: 'teaspoon' },
    ],
    nutrients: {
      calories: 'Approximately 250 per serving',
      protein: 'Approximately 6g',
      fats: 'Approximately 10g',
      carbohydrates: 'Approximately 35g',
      fiber: '0g',
    },
    other: {
      vitamins: ['Vitamin A', 'Vitamin D'],
      minerals: ['Calcium', 'Iron'],
      otherNutrients: [],
    },
    instructions: [
      'Caramelize sugar in a llanera mold and set aside.',
      'In a bowl, whisk egg yolks, condensed milk, and evaporated milk.',
      'Add vanilla extract and mix well.',
      'Pour mixture into the caramelized mold and steam for 30 minutes.',
      'Let it cool before serving.',
    ],
  },
];
